import 'shepherd.js/dist/css/shepherd.css'
import 'swiper/scss'
import 'swiper/css/navigation'
import 'flatpickr/dist/flatpickr.css'
import 'choices.js/public/assets/styles/choices.min.css'
import 'sweetalert2/dist/sweetalert2.min.css'
import 'zuck.js/dist/zuck.min.css'
